# Etapa 1: build da aplicação
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: imagem leve para execução
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Expor a porta que seu back-end usa (ex: 8080)
EXPOSE 8080

# Variáveis de ambiente do banco (opcional)
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://db-pi:5432/postgres \
    SPRING_DATASOURCE_USERNAME=root \
    SPRING_DATASOURCE_PASSWORD=root

# Comando para rodar o app
ENTRYPOINT ["java", "-jar", "app.jar"]